//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nagarro.EmployeePortal.EntityDataModel.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int SubCategotyId { get; set; }
        public string SubCategoryName { get; set; }
        public int CategotyId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
